<%@ Property Name="NameSpace" Type="String" Category="Base" Default="Lic" Optional="True" Description="指定命名空间前缀" %>
<%@ Property Name="BaseClassName" Type="String" Category="Base" Default="kvcms.Exams" Optional="True" Description="指定名称." %>
<%@ Property Name="Discription" Type="String" Category="Context" Description="类名的描述" Default="Lic" %>
<%@ Property Name="DevelopersName" Type="String" Category="Context" Description="类名的描述" Default="Lic" %>

